Django/MYSITE/food/urls.py
from . import views
from django.urls import path
app_name="food"
urlpatterns = [ 
               path('',views.IndexClassView.as_view(),name="index"),
               path('item/',views.item,name="item"),
               path('<int:pk>/',views.FoodDetail.as_view(),name="detail"),
               #add item
               path('add/',views.CreateItem.as_view(),name="create_item"),
               #update item
               path('update/<int:id>/',views.update_item,name="update_item"),
               #delete
               path('delete/<int:id>/',views.delete_item,name="delete_item"),
               ]

Django/MYSITE/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from user import views as user_views
from django.contrib.auth import views as authhenication_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("food/",include('food.urls')),
    path("register/",user_views.register,name="register"),
    path("login/",authhenication_view.LoginView.as_view(template_name='user/login.html'),name="login"),
    path("logout/",authhenication_view.LogoutView.as_view(template_name='user/logout.html'),name="logout"),
    path("profile/",user_views.profilepage,name="profile"),
]



urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/MYSITE/food/models.py
from django.db import models
from django.contrib.auth.models import User 
from django.urls import reverse


# Create your models here.
class Item(models.Model):

    def __str__(self):
          return self.item_name
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://cdn-icons-png.flaticon.com/512/1377/1377194.png")

def get_absolute_url(self):
    return reverse('food:Detail',kwargs ={"pk":self.pk})

Django/MYSITE/user/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    #each user will have a specific profile
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    #on_delete=models.CASCADE -> If you delete the user automatially the profile will get deleted
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    #pip install pillow
    location = models.CharField(max_length=200)

    def __str__(self):
        return self.user.username

Django/MYSITE/food/forms.py
from django import forms 
from .models import Item

class ItemForm(forms.ModelForm):
      class Meta:#tells us what feilds must be present in form
            model= Item #model for Item
            fields = ['item_name','item_desc','item_price','item_image']

Django/MYSITE/user/forms.py
from django import forms
from django.contrib.auth.models import User
#here user is a django predefined user who have username and all
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields=['username','email','password1','password2']

Django/MYSITE/food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.
def index(request):
    item_list = Item.objects.all()
    template = loader.get_template('food/index.html')
    context={'item_list':item_list,}
    return HttpResponse(template.render(context,request))

class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name='item_list'

def item(request):
    return HttpResponse("This is a item")

def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context={
        'item':item,
    }
    return render(request,'food/detail.html',context)

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'

def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form})

#This is a class based view for create item
class CreateItem(CreateView):
    model = Item
    fields=["item_name","item_desc","item_price","item_image"]
    template_name='food/item-form.html'
    def form_valid(self,form):
        form.instance.user_name = self.request.user
        return super.form_valid(form)


def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None,instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form,'item':item})

def delete_item(request,id):
     item = Item.objects.get(id=id)
     if request.method == "POST":
         item.delete()
         return redirect('food:index')
     #to confirm to delete the item we are sending user to another page
     return render(request,'food/item-delete.html',{'item':item})
         

Django/MYSITE/user/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required 
@login_required

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, you have successfully created an account')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request,'user/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'user/profile.html')

Django/MYSITE/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark d-flex">
        <a href="#" class="navbar-brand">Food App</a>
        <div class="navbar-nav">
            <a class="nav-item nav-link me-3" href="{% url 'food:create_item' %}">Add Item</a>
            <a class="nav-item nav-link me-3" href="#">View Item</a>
            <a class="nav-item nav-link me-3" href="#">Delete Item</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
                <a href="{% url 'profile' %}">Profile</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>
    </nav>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html>

Django/MYSITE/food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
             <img height="75px" src="{{ item.item_image }}" class="image-fluid">
        </div>
        <div class="col-md-6">
            <h1>{{ object.item_name }}</h1>
            <h2>{{ object.item_desc }}</h1>
            <h3>${{ object.item_price }}</h1>
            <a href="{% url 'food:delete_item' object.id %}">Delete</a>
        </div>
    </div>
</div>

{% endblock %}

Django/MYSITE/food/templates/food/index.html
{% extends 'food/base.html' %}
{% block body %}
   {% for item in item_list %}
   <div class="row">
      <div class="col-md-3 offset-md-1">
           <img class="image-fluid" height="150px" src="{{ item.item_image }}"/>
      </div>
      <div class="col-md-4 offset-md-1">
           <h3>{{ item.item_name }}</h3>
           <h5>{{ item.item_desc }}</h5>
           <h6>{{ item.item_price }}</h6>
           <h7>{{ item.user_name }}</h7>
      </div>
      <div class="col-md-2 offset-md-1">
        <a href="{% url 'food:detail' item.id %}" class="btn btn-success">details</a>
      </div>
   </div>

   {% endfor %}
{% endblock %}

//THIS IS OLD CODE
<ul>
    {% for item in item_list %}
    <li>
        <a href="{% url 'food:detail' item.id %}">{{ item.id }} -- {{ item.item_name }}</a>
    </li>
    {% endfor %}
</ul>

Django/MYSITE/food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure, You want to delete the item {{item.item_name}}</h2>
    <button type="submit">Confirm</button>
</form>

Django/MYSITE/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add Item
                    </div>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form }}
                        <button class="btn-info" type="submit">Sign Up</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Django/MYSITE/user/templates/user/login.html
{% extends 'food/base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form }}
                        <button class="btn-info" type="submit">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

 -->
<!-- <form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Login</button>
</form> -->

Django/MYSITE/user/templates/user/logout.html
<h2><i>You have been Logged out </i></h2>

Django/MYSITE/user/templates/user/profile.html
<h2>{{ user.username }}</h2>
<img height="100px" width="100px" src="{{ user.profile.image.url }}">

Django/MYSITE/user/templates/user/register.html
{% extends 'food/base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Register
                    </div>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                <br>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button class="btn-info" type="submit">Sign Up</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

<form method="post"></form>
    {% csrf_token %}
    {{ form }}
    <button type="submit">Sign Up</button>
</form>